vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profilePicture:
            uri_prefix: /img/uploads/pfp
            upload_destination: '%kernel.project_dir%/public/img/uploads/pfp'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        profileBackgroundImage:
            uri_prefix: /img/uploads/pbi
            upload_destination: '%kernel.project_dir%/public/img/uploads/pbi'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
